# Generated by Django 4.2.3 on 2023-07-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                ("hashed_url", models.CharField(blank=True, max_length=10)),
                ("pin", models.CharField(blank=True, default="", max_length=6)),
            ],
        ),
    ]
